### ISSUE TITLE
CSS class="correspsearch-eng" bei ul

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-briefe-epub#22]
hier kein abstand vor oder nach der <ul> und keine bullets

**Comment by martinantonmueller** [comment]
sollte jetzt drin sein, check nötig

**Comment by laurauntner** [comment]
epub ist neu gerechnet: funktioniert nicht. bitte bitte zuerst testen (z. b. xhtml im browser).
