### ISSUE TITLE
leeres Werk-Lemma

### ISSUE THREAD

**Issue by laurauntner** [arthur-schnitzler/schnitzler-briefe-epub#31]
vgl. L02702

**Comment by martinantonmueller** [comment]
Hier ist das Problem, dass die implizite Nennung in einem Kommentar passiert. Vermutlich ist es uneinheitlich, ob geschaut wird, ob das @type='implied' in einer note steht oder nicht.

**Comment by martinantonmueller** [comment]
Ich hab’ mehrfach die Einschränkung ``and not(ancestor::tei:note) and not(ancestor::tei:teiHeader)`` ergänzt, mag’ aber heute nicht mehr testen

**Comment by martinantonmueller** [comment]
L02702 funktioniert, also geschlossen
