### ISSUE TITLE
GitHub-Action zum Laufen bringen (Problem mit create-tocs.xml)

### ISSUE THREAD

**Issue by laurauntner** [arthur-schnitzler/schnitzler-briefe-epub#33]

**Comment by laurauntner** [comment]
Die Transformationen funktionieren einzeln alle, aber nicht, wenn sie gemeinsam/mit ant ausgeführt werden. Das Problem sei Zeile 120 in create-tocs.xsl.

**Comment by martinantonmueller** [comment]
gibt keine zeile 120 in create-tocs.XML (und nicht xsl, oder?)

**Comment by laurauntner** [comment]
Verschreiber. Geht um create-content.xsl, Z. 120: <xsl:sort select="//xhtml:meta[@name = 'date']/@content" order="ascending"/>

**Comment by martinantonmueller** [comment]
https://github.com/arthur-schnitzler/schnitzler-briefe-epub/blob/5e9c289b5e87219b01d94b83cb0069181a12d46f/xslt/create-content.xsl#L120

**Comment by martinantonmueller** [comment]
Just a guess: Sind alle Varianten ``@when``, ``@notBefore``, ``@from``ordentlich nach xhtml:meta geschrieben? oder gibt es Fälle, wo @content leer ist? Bzw. würde ich auch das hier machen:
 <xsl:sort select="//xhtml:meta[@name = 'date'][1]/@content" order="ascending"/>

**Comment by laurauntner** [comment]
`//meta[@name = 'date'][2]` gibt’s nie, es ist auch alles auf Vollständigkeit und korrektes ISO-Format geprüft. Und, wie gesagt, es funktioniert ja, wenn es nicht mit den anderen Transformationen gemeinsam ausgeführt wird.

**Comment by martinantonmueller** [comment]
Wenn ich’s lokal mache – pull, nach Anleitung, kommt bei ant inhaltsverzeichnis folgender fehler:

```
[xslt] /Users/oldfiche/Documents/git/schnitzler-briefe-epub/xslt/create-content.xsl:120:0: Fatal Error! Finding root of tree: the context item is not a node
     [xslt] Failed to process null
```

und das stimmt auch, das sort steht in einer collection – das müsste sich aber auf elemente beziehen, glaube ich

**Comment by laurauntner** [comment]
Aber warum sollte es dann funktionieren, wenn es separat ausgeführt wird?

**Comment by martinantonmueller** [comment]
Keine Ahnung. Es scheint auch möglich zu sein, eine collection so zu sortieren:
https://stackoverflow.com/questions/27357327/xslt-2-0-order-of-document-collection

Möglichkeiten, die mir einfallen: 
* Unterschiedliche Saxon-Versionen
