### ISSUE TITLE
Kommafehler

### ISSUE THREAD

**Issue by martinantonmueller** [arthur-schnitzler/schnitzler-briefe-epub#7]
Bei Goldmann an AS, 23.3.1899
steht:
Telegramm1 Blatt
da fehlt das Komma. Fehlt auf der Website auch

**Comment by martinantonmueller** [comment]
das sollte mit dem letzten push behoben sein, muss aber noch überprüft werden

**Comment by laurauntner** [comment]
nicht nachvollziehbar, weil es keinen Brief von PG an AS vom 23. 3. 1899 gibt

**Comment by martinantonmueller** [comment]
Es geht um ein Telegramm, vermutlich war es das: https://schnitzler-briefe.acdh.oeaw.ac.at/L02680.html?
